version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traveloo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped