services:
  - type: web
    name: traveloo-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: ENV
        value: prod
      - fromDotEnv: true
